version: '3.9'

services:
  database:
    build: ./database
    container_name: postgres_db
    environment:
      POSTGRES_DB: hello_world_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    container_name: node_app
    environment:
      DB_NAME: hello_world_db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - database
